#ifndef CAPTURECONSTS_H
#define CAPTURECONSTS_H

#define FRAME_HEIGHT    240
#define FRAME_WIDTH     320

#define IMAGE_CENTER_Y FRAME_HEIGHT/2
#define IMAGE_CENTER_X FRAME_WIDTH/2

#endif //CAPTURECONSTS_H
